ALTER TABLE [dbo].[Album]
    ADD CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED ([idAlbum] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

